### PR TITLE
added a Murata Buzzer

### PR DESCRIPTION
**Pull request by Shackmeister**
Hey guys
should components which can be mounted both ways have a pin 1 indicator?
murata_buzzer

### CODE REVIEW

**Comment by jkriege2** [comment]
Since there may always be a buzzer with the same package, that is polarized, I think the marker does not hurt!

**Comment by jkriege2** [comment]
Since there may always be a buzzer with the same package, that is polarized, I think the marker does not hurt!

**Comment by Shackmeister** [comment]
Goodie :) then it should be ready for merge

**Comment by jkriege2** [comment]
One more comment: courtyard should also surround the pads, but your's overlays the pads.

**Comment by Shackmeister** [comment]
fixed
murata_buzzer

**Comment by jkriege2** [comment]
looks good to me!

Thanks,
JAN

**Pull request merged**
