### PR TITLE
Added generic Buzzer_15x7.5RM7.6

### PR DESCRIPTION
**Pull request by matthijskooijman**
This copies Buzzer_12x9.5RM7.6, but with a different physical size.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @matthijskooijman do you have an example datasheet?

**Comment by poeschlr** [comment]
The 3d path should start with ${KISYS3DMOD}/
And the scale should be 1,1,1

**Comment by matthijskooijman** [comment]
Here's two of them with these specs:

http://nl.mouser.com/ProductDetail/PUI-Audio/AST-01508MR-R/?qs=sGAEpiMZZMuTkJYgZlQcSQcMaqDVgn1UoWe9JyCYcjs%3d
https://www.digikey.com/product-detail/en/cui-inc/CVS-1508/102-2498-ND/279182

> The 3d path should start with ${KISYS3DMOD}/
> And the scale should be 1,1,1

I hadn't originally changed this to stay consistent with the rest of the library. Now, I added a commit that adds ${KISYS3DMOD} to all footprints in the library before adding the new footprint. I also set the scale of the new footprint to 1,1,1 and the position to 0,0,0 (not sure what the convention is for the latter?). I didn't change this in the other footprints, since I think that needs changes to the 3D model as well.

I see the travis check now fails due to problems that were already present in components I changed, but I'm not entirely confident about fixing them (and I don't really want to take the time either).

**Comment by evanshultz** [comment]
@matthijskooijman 
We have ignored existing problems like this when merging new footprints. No problem there.

The Digi-Key link is for a different part, but the Mouser link seems like the buzzer for the footprint.

@jkriege2 @poeschlr 
Do you have other comments or suggestions? This PR improves the whole library and it's a nicer-looking footprint than most in the library. I favor merging for the greater good. Would one (or both) of you either merge this yourself or give me the go-ahead to do it?

Image:
image

**Comment by matthijskooijman** [comment]
> The Digi-Key link is for a different part, but the Mouser link seems like the buzzer for the footprint.

Heh, not sure what happened there. I fixed the link in my previous comment.

**Comment by evanshultz** [comment]
@SchrodingersGat @poeschlr 
Since you commented above, any issues with merging? I think this is good.

Note there are several 3D models not at the proper location/rotation/scaling but that's a pre-existing condition and it's correct on this footprint.

**Comment by SchrodingersGat** [comment]
@matthijskooijman thanks for your contribution

**Pull request merged**
